import type { Metadata } from 'next';
import '../styles/globals.css';
import { Providers } from '@/lib/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='bg-white text-stone-950'>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
