import type { Metadata } from 'next';
import '../styles/globals.css';
import { Providers } from '@/lib/providers';

import { Roboto } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({ weight: ['400', '500', '700'], subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <div className='bg-white text-stone-950'>
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
